[[language]]
name = "ruby"
auto-format = true
language-server = { command = "solargraph" }

[[language]]
name = "python"
file-types = ["py", "pyi"]
roots = ["pyproject.toml", "manage.py"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true